### ISSUE TITLE
Benchmark run fails with "inconsistent arity" message

### ISSUE THREAD

**Issue by c3d** [VictorTaelin/HOC#7]
I get this while running the benchmark:

```
% time cargo run --release -- run -s 134217728 -t 12
    Finished release [optimized] target(s) in 0.05s
     Running `target/release/main run -s 134217728 -t 12`
thread 'main' panicked at 'inconsistent arity on: '(Main)'', src/language/rulebook.rs:95:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
cargo run --release -- run -s 134217728 -t 12  0.08s user 0.02s system 99% cpu 0.105 total
```

Observed the exact same problem on two distinct machines with different operating systems:
1. Apple MacBook Pro with M1 Pro, macOS Ventura 13.1
2. 64-CPU Xeon Gold 5128 Linux server 

The stack trace for a debug build looks like this:

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/core/src/panicking.rs:64:14
   2: main::language::rulebook::add_group::register
             at ./src/language/rulebook.rs:95:15
   3: main::language::rulebook::add_group
             at ./src/language/rulebook.rs:128:5
   4: main::language::rulebook::gen_rulebook
             at ./src/language/rulebook.rs:146:7
   5: main::api::eval
             at ./src/api.rs:18:14
   6: main::run_cli
             at ./src/main.rs:79:32
   7: main::main
             at ./src/main.rs:67:21
   8: core::ops::function::FnOnce::call_once
             at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/core/src/ops/function.rs:250:5
```

**Comment by c3d** [comment]
Apparently, `smap.len()` is 1, whereas `args.len()` is 0.

**Comment by VictorTaelin** [comment]
Savio solved this, ty!
